name: "Github action for generating random and unique names."
description: "Create a random name and output it to Github Actions environment variables"
inputs:
  separator:
    description:
      "A string separator to be used for separate the words generated.
      The default separator is set to `_`."
    required: false
    default: "_"
  length:
    description:
      "The default value is set to 3 and it will return a name composed of 3 words.
      This values must be equal or minor to the number of dictionaries defined (3 by default).
      Setting the length to a value of 4 will throw an error when only 3 dictionaries are provided."
    required: false
    default: "3"
  style:
    description:
      "The default value is set to lowerCase and it will return a lower case name.
      By setting the value to upperCase, the words, will be returned with all the letters in upper case format.
      The capital option will capitalize each word of the unique name generated.
      `lowerCase | upperCase | capital`."
    required: false
    default: lowerCase
  seed:
    description:
      "A seed is used when wanting to deterministically generate a name.
      As long as the provided seed is the same the generated name will also always be the same.
      `number` | `string`."
    required: false
outputs:
  name:
    description: "The generated random name output."
runs:
  using: node16
  main: index.mjs
  pre: npm ci
